sudo: required
dist: trusty
language: node_js
node_js:
  # LTS version
  - "8.0"
cache:
  directories:
    - node_modules
install:
  - npm install
# command to run tests
script:
  - mocha --exit
after_script: 
# "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
  - npm run coveralls

